package com.tianxin.Util;


public class Constants {

    // 存储字符串标识
    public static final String USERINFO = "userInfo";
    public static final String ACCOUNT = "account";
    public static final String PWD = "password";
    public static final String model = "model";
    public static final String ROOM = "room";
    public static final String AUTO_LOGIN = "auto_login";
    public static final String LOGOUT = "logout";
    public static final String ICON_URL = "icon_url";
    public static final String CHAT_INFO = "chatInfo";
    public static final String MONEYLIST1 = "moneylist1";
    public static final String MONEYLIST2 = "moneylist2";
    public static final String MONEYLIST3 = "moneylist3";
    public static final String configmsg = "configmsg";
    public static final String dadelist = "dadelist";
    public static final String IS_OFFLINE_PUSH_JUMP = "is_offline_push";
    public static final String TITLE = "title";
    public static final String content = "content";
    public static final String PATHVIDEO = "pathvideo";
    public static final String PATHIMG = "pathimg";
    public static final String POSITION = "position";
    public static final String TOTALPAGE = "totalPage";
    public static final String PAGE = "page";
    public static final String ENDTOTALPAGE = "endtotalPage";
    public static final String USERID = "userid";
    public static final String TYPE = "type";
    public static final String mcontent = "mcontent";
    public static final String status = "status";
    public static final String style = "style";
    public static final String Edit = "edit";
    public static final String Orderid = "orderid";
    public static final String Token = "token";
    public static final String accessToken = "accessToken";
    public static final String Parent = "parent";
    public static final String VIDEOURL = "videoUrl";
    public static final String playvideo = "video";
    public static final String JSON = "json";
    public static final String List = "list";
    public static final String PERIMG = "perimg";
    public static final String TUPIANZJ = "tupianzj";
    public static final String zuserid = "zuserid";
    public static final String username = "username";
    public static final String password = "password";
    public static final String touserid = "touserid";
    public static final String hostuserid = "hostuserid";
    public static final String reason = "reason";
    public static final String PATH = "path";
    public static final String image = "image";
    public static final String money = "money";
    public static final String trendid = "trendid";
    public static final String suserid = "suserid";
    public static final String gif = "gif";
    public static final String perimg = "perimg";
    public static final String id = "id";
    public static final String sex = "sex";
    public static final String province = "province";
    public static final String city = "city";
    public static final String district = "district";
    public static final String selected_images = "selected_images";
    public static final String anchorid = "anchorid";
    public static final String mobile = "mobile";
    public static final String code = "code";
    public static final String jinbi = "jinbi";
    public static final String tid = "tid";
    public static final String tencent = "tencent";
    public static final String love = "love";
    public static final String key = "key";
    public static final String address = "address";
    public static final int TENCENT0 = 0;
    public static final int TENCENT = 1;
    public static final int TENCENT2 = 2;
    public static final int TENCENT3 = 3;
    public static final int TENCENT4 = 4;
    public static final int TENCENT5 = 5;
    public static final int TENCENT6 = 6;
    public static final String VIP = "vip";
    public static final int requestCode = 2000;
    public static final int REQUEST_CODE = 1000;
    public static final int sussess = 200;
    public static final String Msg = "msg";
    public static final String NAME = "name";
    public static final String QRCODE = "qrcode";
    public static final int sText = 1;
    public static final int Images = 2;
    public static final int Video = 3;
    public static final int OnImages = 1; //默认没有图片


    public static final String uid = "uid";
    public static final String roomName = "roomName";
    public static final String roomnumber = "roomnumber";
    public static final String ALL = "all";
    public static String className = "MyService";
    public static String random = "random";
    public static String cityid = "cityid";
    public static String alias = "alias";
    public static String quantity = "quantity";
    public static String descshow = "descshow";
    public static String bookdatetime = "bookdatetime";
    public static String phone = "phone";
    public static String login = "login";
    public static String viecode = "viecode";
    public static String truename = "truename";
    public static String showview = "showview";
    public static String message = "message";
    public static String wxpay = "wxpay";

    public final static String whatsnew = "whatsnew";            //动态相册
    public final static String WechatMoments = "WechatMoments";  //动态视频
    public final static String qrcode = "qrcode";                //结算信息
    public final static String picture = "picture";              //相册图片
    public final static String avatar = "avatar";                //个人头像
    public final static String attestation = "attestation";      //身份证
    public final static String video = "video";                  //相册视频
    public static String jwd = "jwd";
    public static String remarks = "remarks";
    public static String Key = "key";
    public static String agent = "agent";                       //代理比例
    public static String qq="qq";
    public static String price="price";
    public static String channelid="channelid";
    public static String amount="amount";
}
